spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/fwc_album_app
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver

    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true

            path: /h2-console


    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    security:

