/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.henriqueborba.fwcalbumapp.frontend.views.login;

import edu.henriqueborba.fwcalbumapp.frontend.controllers.LoginController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

import javax.swing.*;

/**
 *
 * @author henrique
 */
@Component
public class LoginView extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form teste
     */
    @Autowired
    public LoginView(@Lazy LoginController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entryButton = new javax.swing.JButton();
        loginTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        CadLabel = new javax.swing.JLabel();
        CadLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entryButton.setBackground(new java.awt.Color(253, 206, 80));
        entryButton.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        entryButton.setForeground(new java.awt.Color(121, 20, 53));
        entryButton.setText("Entrar");
        entryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(entryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 544, 300, 30));

        loginTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTFActionPerformed(evt);
            }
        });
        getContentPane().add(loginTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 300, 40));
        getContentPane().add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 300, 40));

        passwordLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Senha");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        loginLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setText("Email");
        getContentPane().add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        CadLabel.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        CadLabel.setForeground(new java.awt.Color(255, 255, 255));
        CadLabel.setText("Não possui uma conta ? ");
        getContentPane().add(CadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 780, -1, -1));

        CadLabel1.setBackground(new java.awt.Color(253, 206, 80));
        CadLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        CadLabel1.setForeground(new java.awt.Color(253, 206, 80));
        CadLabel1.setText("Cadastre-se");
        CadLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(CadLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 780, -1, -1));

        background.setIcon(new javax.swing.ImageIcon("/home/henrique/projects/java/POO/fwcalbumapp/assets/images/background_login.png")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    private void loginTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTFActionPerformed

    private void entryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryButtonActionPerformed
      controller.login(loginTF.getText(), String.valueOf(passwordTF.getPassword()));
    }//GEN-LAST:event_entryButtonActionPerformed

    private void CadLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadLabel1MouseClicked
        controller.redirectToRegister();
    }//GEN-LAST:event_CadLabel1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadLabel;
    private javax.swing.JLabel CadLabel1;
    private javax.swing.JLabel background;
    private javax.swing.JButton entryButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginTF;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTF;
    // End of variables declaration//GEN-END:variables
}
